using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace studeehub.Persistence.Migrations
{
	/// <inheritdoc />
	public partial class PomodoroSetting : Migration
	{
		/// <inheritdoc />
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.AlterColumn<DateTime>(
				name: "Start",
				table: "PomodoroSessions",
				type: "datetime2",
				nullable: true,
				oldClrType: typeof(DateTime),
				oldType: "datetime2");

			migrationBuilder.AddColumn<int>(
				name: "CycleIndex",
				table: "PomodoroSessions",
				type: "int",
				nullable: false,
				defaultValue: 0);

			migrationBuilder.AddColumn<TimeSpan>(
				name: "Duration",
				table: "PomodoroSessions",
				type: "time",
				nullable: false,
				defaultValue: new TimeSpan(0, 0, 0, 0, 0));

			migrationBuilder.AddColumn<bool>(
				name: "IsAutoGenerated",
				table: "PomodoroSessions",
				type: "bit",
				nullable: false,
				defaultValue: false);

			migrationBuilder.AddColumn<string>(
				name: "Status",
				table: "PomodoroSessions",
				type: "nvarchar(max)",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<string>(
				name: "Type",
				table: "PomodoroSessions",
				type: "nvarchar(max)",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<Guid>(
				name: "PomodoroSettingId",
				table: "AspNetUsers",
				type: "uniqueidentifier",
				nullable: false,
				defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

			migrationBuilder.CreateTable(
				name: "PomodoroSettings",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					WorkDuration = table.Column<int>(type: "int", nullable: false),
					ShortBreakDuration = table.Column<int>(type: "int", nullable: false),
					LongBreakDuration = table.Column<int>(type: "int", nullable: false),
					LongBreakInterval = table.Column<int>(type: "int", nullable: false),
					AutoStartNext = table.Column<bool>(type: "bit", nullable: false)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_PomodoroSettings", x => x.Id);
					table.ForeignKey(
						name: "FK_PomodoroSettings_AspNetUsers_UserId",
						column: x => x.UserId,
						principalTable: "AspNetUsers",
						principalColumn: "Id",
						onDelete: ReferentialAction.Cascade);
				});

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0001-4a1b-8c1d-000000000001"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5001), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5002) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0002-4a1b-8c1d-000000000002"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5010), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5010) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0003-4a1b-8c1d-000000000003"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5012), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5013) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0004-4a1b-8c1d-000000000004"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5016), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5016) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0005-4a1b-8c1d-000000000005"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5018), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(5018) });

			migrationBuilder.UpdateData(
				table: "AspNetUsers",
				keyColumn: "Id",
				keyValue: new Guid("09097277-2705-40c2-bce5-51dbd1f4c1e6"),
				columns: new[] { "PasswordHash", "PomodoroSettingId", "RefreshTokenExpiryTime" },
				values: new object[] { "AQAAAAIAAYagAAAAEBFnvPlWrUs57+l/H9DDYcwHsfHTZ+QMUk01Ji7fo6Yy9oqXVSYEESRxUZOaL5vrJw==", new Guid("00000000-0000-0000-0000-000000000000"), new DateTime(2025, 10, 19, 16, 16, 4, 497, DateTimeKind.Utc).AddTicks(3739) });

			migrationBuilder.UpdateData(
				table: "AspNetUsers",
				keyColumn: "Id",
				keyValue: new Guid("33f41895-b601-4aa1-8dc4-8229a9d07008"),
				columns: new[] { "PasswordHash", "PomodoroSettingId", "RefreshTokenExpiryTime" },
				values: new object[] { "AQAAAAIAAYagAAAAENEnOtD/ZISict5GsZZjDR9btxc0h07v3eChyqOyG8RJunDNYgA6FDfnKHqAzED6JA==", new Guid("00000000-0000-0000-0000-000000000000"), new DateTime(2025, 10, 19, 16, 16, 4, 448, DateTimeKind.Utc).AddTicks(4914) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1001-4a1b-8c1d-000000000101"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4854), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4858) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1002-4a1b-8c1d-000000000102"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4870), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4871) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1003-4a1b-8c1d-000000000103"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4952), new DateTime(2025, 10, 12, 16, 16, 4, 546, DateTimeKind.Utc).AddTicks(4952) });

			migrationBuilder.CreateIndex(
				name: "IX_PomodoroSettings_UserId",
				table: "PomodoroSettings",
				column: "UserId",
				unique: true);
		}

		/// <inheritdoc />
		protected override void Down(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropTable(
				name: "PomodoroSettings");

			migrationBuilder.DropColumn(
				name: "CycleIndex",
				table: "PomodoroSessions");

			migrationBuilder.DropColumn(
				name: "Duration",
				table: "PomodoroSessions");

			migrationBuilder.DropColumn(
				name: "IsAutoGenerated",
				table: "PomodoroSessions");

			migrationBuilder.DropColumn(
				name: "Status",
				table: "PomodoroSessions");

			migrationBuilder.DropColumn(
				name: "Type",
				table: "PomodoroSessions");

			migrationBuilder.DropColumn(
				name: "PomodoroSettingId",
				table: "AspNetUsers");

			migrationBuilder.AlterColumn<DateTime>(
				name: "Start",
				table: "PomodoroSessions",
				type: "datetime2",
				nullable: false,
				defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
				oldClrType: typeof(DateTime),
				oldType: "datetime2",
				oldNullable: true);

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0001-4a1b-8c1d-000000000001"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1079), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1080) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0002-4a1b-8c1d-000000000002"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1091), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1091) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0003-4a1b-8c1d-000000000003"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1094), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1094) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0004-4a1b-8c1d-000000000004"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1097), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1098) });

			migrationBuilder.UpdateData(
				table: "Achievements",
				keyColumn: "Id",
				keyValue: new Guid("a1f2c3d4-0005-4a1b-8c1d-000000000005"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1099), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1100) });

			migrationBuilder.UpdateData(
				table: "AspNetUsers",
				keyColumn: "Id",
				keyValue: new Guid("09097277-2705-40c2-bce5-51dbd1f4c1e6"),
				columns: new[] { "PasswordHash", "RefreshTokenExpiryTime" },
				values: new object[] { "AQAAAAIAAYagAAAAEK+0UHkir8hlN3Ohf4noeerzmeShs4ot1esI7GdYGCvzN2VuNRl7bSCGsOiL6sUtXA==", new DateTime(2025, 10, 19, 10, 40, 27, 871, DateTimeKind.Utc).AddTicks(9244) });

			migrationBuilder.UpdateData(
				table: "AspNetUsers",
				keyColumn: "Id",
				keyValue: new Guid("33f41895-b601-4aa1-8dc4-8229a9d07008"),
				columns: new[] { "PasswordHash", "RefreshTokenExpiryTime" },
				values: new object[] { "AQAAAAIAAYagAAAAEH8KT8J+aOiN9ic5bPI9cd3GeShXaSLeA/j7FZgv8hox3MQyK4hrvFuLE7bPH78Emw==", new DateTime(2025, 10, 19, 10, 40, 27, 823, DateTimeKind.Utc).AddTicks(2936) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1001-4a1b-8c1d-000000000101"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1016), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1017) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1002-4a1b-8c1d-000000000102"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1029), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1029) });

			migrationBuilder.UpdateData(
				table: "SubscriptionPlans",
				keyColumn: "Id",
				keyValue: new Guid("d2f1c3a4-1003-4a1b-8c1d-000000000103"),
				columns: new[] { "CreatedAt", "UpdatedAt" },
				values: new object[] { new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1036), new DateTime(2025, 10, 12, 10, 40, 27, 920, DateTimeKind.Utc).AddTicks(1036) });
		}
	}
}
