namespace studeehub.Application.DTOs.Responses.PomodoroSession
{
	public class GetSessionResponse
	{
		public Guid Id { get; set; }
		public Guid UserId { get; set; }
		public string Type { get; set; } = null!;
		public string Status { get; set; } = null!;
		public DateTime? Start { get; set; }
		public DateTime? End { get; set; }
		public TimeSpan Duration { get; set; }
		public int CycleIndex { get; set; }
		public bool IsAutoGenerated { get; set; }
	}
}
