using Mapster;
using studeehub.Application.DTOs.Responses.PomodoroSession;
using studeehub.Domain.Entities;

namespace studeehub.Application.Mappings
{
	public class PomodoroSessionRegister : IRegister
	{
		public void Register(TypeAdapterConfig config)
		{
			config.NewConfig<PomodoroSession, GetSessionResponse>()
				.Map(dest => dest.Id, src => src.Id)
				.Map(dest => dest.UserId, src => src.UserId)
				.Map(dest => dest.Type, src => src.Type)
				.Map(dest => dest.Status, src => src.Status)
				.Map(dest => dest.Start, src => src.Start)
				.Map(dest => dest.End, src => src.End)
				.Map(dest => dest.Duration, src => src.Duration)
				.Map(dest => dest.CycleIndex, src => src.CycleIndex)
				.Map(dest => dest.IsAutoGenerated, src => src.IsAutoGenerated);
		}
	}
}
