using studeehub.Domain.Enums.Pomodoros;

namespace studeehub.Domain.Entities
{
	public class PomodoroSession
	{
		public Guid Id { get; set; } = Guid.NewGuid();
		public Guid UserId { get; set; }

		public PomodoroType Type { get; set; }
		public PomodoroStatus Status { get; set; } = PomodoroStatus.Active;

		public DateTime? Start { get; set; }
		public DateTime? End { get; set; }
		public TimeSpan Duration { get; set; } // expected duration (e.g., 25min or 5min)

		public int CycleIndex { get; set; } // 1,2,3,4 — which Pomodoro of this batch
		public bool IsAutoGenerated { get; set; } = false; // break sessions auto-generated by system

		public virtual User User { get; set; } = null!;
	}
}
